M48
; DRILL file {KiCad 7.0.8} date Thu Nov  9 16:50:53 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-09T16:50:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X5.2425Y-1.4116
X5.2425Y-3.26
X6.2075Y-1.4116
X6.2075Y-3.26
T0
M30
